services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    sylius.google_tag_manager.enhanced_ecommerce_tracking.cart.listener.add_to_cart:
        class: StefanDoorn\SyliusGtmEnhancedEcommercePlugin\EventListener\CartListener
        arguments:
            - '@session'
            - '@sylius.google_tag_manager.enhanced_ecommerce_tracking.tag_manager.cart'
            - "@sylius.google_tag_manager.enhanced_ecommerce.tracking.google_implementation_enabled"
        tags:
            - { name: kernel.event_listener, event: sylius.order_item.post_add, method: onAddToCart }

    sylius.google_tag_manager.enhanced_ecommerce_tracking.cart.listener.remove_from_cart:
        class: StefanDoorn\SyliusGtmEnhancedEcommercePlugin\EventListener\CartListener
        arguments:
            - '@session'
            - '@sylius.google_tag_manager.enhanced_ecommerce_tracking.tag_manager.cart'
            - "@sylius.google_tag_manager.enhanced_ecommerce.tracking.google_implementation_enabled"
        tags:
            - { name: kernel.event_listener, event: sylius.order_item.post_remove, method: onRemoveFromCart }

    sylius.google_tag_manager.enhanced_ecommerce_tracking.cart.listener.controller:
        class: StefanDoorn\SyliusGtmEnhancedEcommercePlugin\EventListener\CartListener
        arguments:
            - '@session'
            - '@sylius.google_tag_manager.enhanced_ecommerce_tracking.tag_manager.cart'
            - "@sylius.google_tag_manager.enhanced_ecommerce.tracking.google_implementation_enabled"
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
