services:
    sylius.google_tag_manager_enhanced_ecommerce.cart.block_event_listener.sylius.shop.product.show.before_add_to_cart:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - 'GtmEnhancedEcommercePlugin::Cart/product_show.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.product.show.before_add_to_cart, method: onBlockEvent }

    sylius.google_tag_manager_enhanced_ecommerce.cart.block_event_listener.layout.javascripts:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - 'GtmEnhancedEcommercePlugin::Cart/javascripts.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.javascripts, method: onBlockEvent }
