services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    sylius.google_tag_manager.enhanced_ecommerce_tracking.product_detail.listener.sylius.shop.layout.head:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@SyliusGtmEnhancedEcommercePlugin/ProductDetail/head.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.head, method: onBlockEvent }

    sylius.google_tag_manager.enhanced_ecommerce_tracking.product_detail.listener.sylius.shop.layout.after_body:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@SyliusGtmEnhancedEcommercePlugin/ProductDetail/foot.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.after_body, method: onBlockEvent }

    sylius.google_tag_manager.enhanced_ecommerce_tracking.product_detail.listener.product.show.after_product_header:
        class: SyliusGtmEnhancedEcommercePlugin\EventListener\ProductShowBlockAfterProductHeaderListener
        arguments:
            - '@@SyliusGtmEnhancedEcommercePlugin/ProductDetail/variants.html.twig'
            - '@sylius.google_tag_manager.enhanced_ecommerce.tracking.resolver.product_detail_impression_data'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.product.show.after_product_header, method: onProductShow }
