services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    sylius.google_tag_manager_enhanced_ecommerce.product_clicks.block_event_listener.layout.javascripts:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@SyliusGtmEnhancedEcommercePlugin/ProductClicks/javascripts.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.javascripts, method: onBlockEvent }
